In [ ]:
# Zhijie Chen
# 10444907
# EE551 final project


In [ ]:
import numpy as np

In [ ]:
# X = (hours sleeping, hours studying), y = score on test
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)

# scale units
X = X/np.amax(X, axis=0) # maximum of X array
y = y/100 # max test score is 100

In [3]:
class Neural_Network(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3

        #weights
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize) # (3x2)
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize) # (3x1)
    
    #forward propagation
    def forward(self, X):
        self.z = np.dot(X, self.W1)
        # activation function
        self.z2 = self.sigmoid(self.z) 
        self.z3 = np.dot(self.z2, self.W2) 
        o = self.sigmoid(self.z3) # final activation function
        return o 

    def sigmoid(self, s):
        # activation function 
        return 1/(1+np.exp(-s))
    
    #derivative of sigmoid
    def sigmoidPrime(self, s):
       
        return s * (1 - s)
    
    def backward(self, X, y, o):
        self.o_error = y - o # error in output
        self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.W2.T) # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error

        self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights

    def train (self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)



In [13]:
NN = Neural_Network()
for i in range(1000): # trains the NN 1,000 times
  print("Input: \n",str(X))
  print("Actual Output: \n" + str(y))
  print("Predicted Output:\n"+str(NN.forward(X)))
  print("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) # mean sum squared loss
  print("\n")
  NN.train(X, y)

Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.50351054]
 [0.45794733]
 [0.50360418]]
Loss: 
0.16147051563528544


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.54709665]
 [0.49969571]
 [0.54979085]]
Loss: 
0.12820611783454078


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.58547871]
 [0.53681274]
 [0.59025236]]
Loss: 
0.10206771686902595


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.61904877]
 [0.56946158]
 [0.62539015]]
Loss: 
0.08166752962393363


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted 

Predicted Output:
[[0.90088512]
 [0.86199031]
 [0.90584696]]
Loss: 
0.00020682208730780804


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.900898  ]
 [0.86200312]
 [0.90585534]]
Loss: 
0.000206763540710049


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90091061]
 [0.86201561]
 [0.90586345]]
Loss: 
0.00020670554381237494


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90092294]
 [0.86202777]
 [0.9058713 ]]
Loss: 
0.00020664807042689105


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90093502]
 [0.86203962]
 [0.90587891]]
Loss: 
0.00020659109566364723


Input: 
 [[0.66666667 1.        ]

 [0.89]]
Predicted Output:
[[0.90158249]
 [0.86245029]
 [0.90595821]]
Loss: 
0.0001999576838537612


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90158463]
 [0.86245025]
 [0.90595643]]
Loss: 
0.00019991244798426826


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90158676]
 [0.8624502 ]
 [0.90595465]]
Loss: 
0.00019986722889613623


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90158888]
 [0.86245015]
 [0.90595286]]
Loss: 
0.0001998220265552592


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.901591  ]
 [0.86245008]
 [0.90595106]]
Loss: 
0.00019977684092852346


Input: 
 [[0.66666667 1.

Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.9018834 ]
 [0.86240107]
 [0.90564559]]
Loss: 
0.00019292033223043255


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90188518]
 [0.86240069]
 [0.90564361]]
Loss: 
0.0001928775551682543


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90188696]
 [0.86240031]
 [0.90564164]]
Loss: 
0.00019283479241045576


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90188874]
 [0.86239992]
 [0.90563966]]
Loss: 
0.00019279204394517094


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output:
[[0.90207525]
 [0.86235963]
 [0.90543222]]
Loss: 
0.0001883394028438189


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90207699]
 [0.86235926]
 [0.90543029]]
Loss: 
0.000188298117592829


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90207873]
 [0.86235888]
 [0.90542836]]
Loss: 
0.00018825684542168303


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90208047]
 [0.86235851]
 [0.90542643]]
Loss: 
0.00018821558631976115


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90208221]
 [0.86235813]
 [0.90542449]]
Loss: 
0.0001881743402764632


Input: 
 [[0.66666667 1.        ]
 

Predicted Output:
[[0.90232456]
 [0.86230645]
 [0.90515627]]
Loss: 
0.00018248449511878298


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90232626]
 [0.86230609]
 [0.9051544 ]]
Loss: 
0.0001824450007283932


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90232796]
 [0.86230574]
 [0.90515253]]
Loss: 
0.00018240551798434757


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90232966]
 [0.86230538]
 [0.90515065]]
Loss: 
0.00018236604687746016


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90233135]
 [0.86230502]
 [0.90514878]]
Loss: 
0.00018232658739855595


Input: 
 [[0.66666667 1.        

 [0.89]]
Predicted Output:
[[0.90251316]
 [0.86226705]
 [0.90494876]]
Loss: 
0.00017813147803165657


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90251483]
 [0.8622667 ]
 [0.90494692]]
Loss: 
0.0001780932329251596


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.9025165 ]
 [0.86226636]
 [0.90494509]]
Loss: 
0.00017805499849000788


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90251817]
 [0.86226601]
 [0.90494326]]
Loss: 
0.00017801677471796312


Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.90251984]
 [0.86226567]
 [0.90494143]]
Loss: 
0.0001779785616008


Input: 
 [[0.66666667 1.   